apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dev 
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: mycontainer
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
            - containerPort: 80
